name = "HeapHammer Diagnostics Pack"
author = "dwurdy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9cf179318850472e645145e885919a3a8f02860f061a7154551db4839466d74"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
