name = "HeapHammer Diagnostics Pack"
author = "dwurdy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9755ac397a6d4a3fffbcc062e4eaf0b42e594acf06c89c9eea3ae8ca210a38e"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
