name = "HeapHammer Diagnostics Pack"
author = "dwurdy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d104dde5ddcc1218e6cad8563641398af046e2433e79fee3b581531475f0d27"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
