name = "HeapHammer Diagnostics Pack"
author = "dwurdy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a703be9b2a9d52eb398ed1bebdc546db922bc2b1d0a7e3b81d22e4211ec71fb5"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
