name = "HeapHammer Diagnostics Pack"
author = "dwurdy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"
license = "LGPL-3.0-only"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30054b9dfc7d366e33cfd71ab9dd3514318dd5291791052ed2665a9fc2781991"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
