name = ""
author = "dwurdy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"
license = "LGPL-3.0-only"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb4dfbdded447aff25999203cff1b53d362e5b5fa179ae3e221c4a48f7c077a9"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
