name = "HeapHammer Diagnostics Pack"
author = "dwurdy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9062405e4c2a2a2da89a3ab585628079f151223dc0e189285ae84e10f2a7a0db"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
